//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Billid { get; set; }
        public Nullable<int> HouseRent { get; set; }
        public Nullable<int> Internet { get; set; }
        public Nullable<int> Laundry { get; set; }
        public Nullable<int> FoodBill { get; set; }
        public Nullable<int> MonthId { get; set; }
        public Nullable<int> RegistrationId { get; set; }
    
        public virtual Month Month { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
