//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillAudit
    {
        public int BillAuditId { get; set; }
        public Nullable<int> Billid { get; set; }
        public Nullable<int> MessingId { get; set; }
    }
}
