//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messing
    {
        public int MessingId { get; set; }
        public Nullable<int> WeekdayId { get; set; }
        public Nullable<int> MealTypeId { get; set; }
        public Nullable<int> FoodListId { get; set; }
        public Nullable<int> Price { get; set; }
        public string OrderDate { get; set; }
        public Nullable<int> MonthId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<bool> Hostory { get; set; }
        public Nullable<int> BillId { get; set; }
    
        public virtual FoodList FoodList { get; set; }
        public virtual MealType MealType { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual Weekday Weekday { get; set; }
    }
}
